resolver: lts-13.17
flags: {}
packages:
- location: .
extra-deps:
  [ Yampa-0.13
  , yampa-gloss-0.2
  , simple-affine-space-0.1
  , proteaaudio-0.7.1.0
  , SDL-mixer-0.6.3.0
  , SDL-0.6.7.0
  ]
extra-package-dbs: []
